version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
     - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: eshop
      POSTGRES_PASSWORD: password

  web:
    image: com.pivstone/eshop:latest
    links:
      - db
    ports:
      - 8080:8080
    environment:
      POSTGRES_PASSWORD: password